service: aws-lambda-crud-node
frameworkVersion: '3'
useDotenv: true

provider:
  name: aws
  runtime: nodejs18.x
  region: ${env:AWS_REGION}
  iamRoleStatements:
    - Effect: Allow
      Action:
        - dynamoDB:*
      Resource:
        -  ${env:DYNAMODB}

functions:
  hello:
    handler: src/index.handler
    events:
      - httpApi:
          path: /
          method: get

  createTask:
    handler: src/addTask.addTask
    events:
      - httpApi:
          path: /tasks
          method: post

  getTasks:
    handler: src/getTasks.getTasks
    events:
      - httpApi:
          path: /tasks
          method: get

resources:
  Resources:
    TaskTable:
      Type: AWS::DynamoDB::Table
      Properties:
        TableName: ${env:DYNAMODB_TABLE}
        BillingMode: PAY_PER_REQUEST
        AttributeDefinitions:
          - AttributeName: id
            AttributeType: S
        KeySchema:
          - AttributeName: id
            KeyType: HASH